# Generated by Django 5.0.6 on 2024-05-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_prediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('region', models.TextField()),
                ('crop', models.TextField()),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
