# Generated by Django 5.0.6 on 2024-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barley",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("region", models.TextField()),
                ("prediction", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Bean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("region", models.TextField()),
                ("prediction", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Corn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("region", models.TextField()),
                ("prediction", models.FloatField()),
            ],
        ),
    ]
